const serviceData = [
  {
    id: 1,
    img: "images/blog/blog-1.jpg",
    date: "22 june 2023",
    title: "Telehealth Services Are Ready To Help Your Family",
    data: "Telehealth is the use of digital communication tools, such as video calls, phone consultations, and mobile apps, to connect patients with healthcare professionals. This innovative approach allows individuals to receive medical care without the need for in-person visits, saving time and reducing exposure to illnesses.",
    btn: "Read More",
  },
  {
    id: 2,
    img: "images/blog/blog-2.jpg",
    date: "22 june 2023",
    title: "Doccure – Making your clinic painless visit",
    data: "In today’s fast-paced world, convenience is key, especially when it comes to healthcare. Long waiting hours, scheduling issues, and last-minute cancellations make clinic visits a hassle for both patients and doctors. This is where Doccure steps in, revolutionizing the way people book doctor appointments and manage healthcare visits.",
    btn: "Read More",
  },
  {
    id: 3,
    img: "images/blog/blog-3.jpg",
    date: "22 june 2023",
    title: "What are the benefits of Online Doctor Booking",
    data: "In today's fast-paced world, technology has revolutionized every aspect of our lives, including healthcare. Online doctor booking platforms have emerged as a convenient and efficient way for patients to connect with healthcare professionals without the hassle of waiting in long queues or making endless phone calls. ",

    btn: "Read More",
  },
  {
    id: 4,
    img: "images/blog/blog-4.jpg",
    date: "22 june 2023",
    title: "From Click to Care",
    data: "Gone are the days of long waiting times and endless phone calls to schedule a doctor’s appointment. Online doctor booking platforms allow patients to connect with healthcare professionals with just a few clicks. These platforms provide real-time availability, appointment scheduling, and even video consultations, making healthcare more accessible than ever before.",
    btn: "Read More",
  },
  {
    id: 5,
    img: "images/blog/blog-5.jpg",
    date: "22 june 2023",
    title: "The Smart Way to See a Doctor: Benefits of Online Appointments",
    data: "In today’s fast-paced world, convenience is key. Whether it’s shopping, banking, or even working, technology has transformed how we complete everyday tasks. The healthcare industry is no exception. With the rise of online doctor appointments, patients can now access healthcare services from the comfort of their homes. ",
    btn: "Read More",
  },
  {
    id: 6,
    img: "images/blog/blog-6.jpg",
    date: "22 june 2023",
    title: "Say Goodbye to Long Queues",
    data: "Waiting in long queues at hospitals and clinics is a frustrating experience that wastes valuable time and energy. With the rise of digital healthcare solutions, online doctor booking platforms have transformed the way patients access medical care. Now, you can schedule appointments with just a few clicks, eliminating unnecessary wait times and ensuring a seamless healthcare experience.",
    btn: "Read More",
  },
  {
    id: 7,
    img: "images/blog/blog-7.jpg",
    date: "22 june 2023",
    title: "Your Doctor, Just a Click Away",
    data: "Online doctor booking is a digital solution that allows patients to schedule consultations with healthcare professionals at their convenience. Whether it’s a routine check-up, a specialist appointment, or an urgent medical concern, you can connect with a qualified doctor with just a few taps on your smartphone or clicks on your computer.",
    btn: "Read More",
  },
  {
    id: 8,
    img: "images/blog/blog-8.jpg",
    date: "22 june 2023",
    title: "The Smart Way to See a Doctor",
    data: "In today’s fast-paced world, finding time for a doctor’s visit can be challenging. Long wait times, scheduling conflicts, and travel hassles often make healthcare less accessible. Fortunately, technology has transformed the way we approach medical consultations. Online doctor booking is the smart, convenient",
  },
  {
    id: 9,
    img: "images/blog/blog-9.jpg",
    date: "22 june 2023",
    title: "24/7 Healthcare Access",
    data: "Gone are the days of long waiting times and endless phone calls to schedule a doctor’s appointment. Online doctor booking platforms allow patients to connect with healthcare professionals with just a few clicks. These platforms provide real-time availability, appointment scheduling, and even video consultations",
    btn: "Read More",
  },
];
export default serviceData;
